/**:
  ros__parameters:
    engineSettings:
      gravity: [0.0, 0.0, -9.81]  
      timeStep: 0.001
      numSolverIterations: 150
      useSplitImpulse: true
      splitImpulsePenetrationThreshold: -0.04
      enableConeFriction: true
      deterministicOverlappingPairs: 1
      pedestal_reset_time : 1.0      
      response_wait_time : 5.0
      loading_wait_time : 5.0

    simSettings:

      realtime_flag: false
      use_gui: true
      enable_plotting: false